config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'pages/about'

  resources :sweets
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

root to: redirect('/sweets')
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
end

app/models/sweet.rb
class Sweet < ApplicationRecord
  mount_uploader :picture, PictureUploader
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController <  ApplicationController
  # GET /bookings/new
  def new
    @booking = Booking.new
  end
  def create
    @booking = Booking.new(booking_params)

    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end
  private

    def booking_params
      params.require(:booking).permit(:name,:details,:email)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/sweets_controller.rb
class SweetsController < ApplicationController
  before_action :set_sweet, only: [:show, :edit, :update, :destroy]

  # GET /sweets
  # GET /sweets.json
  def index
    @sweets = Sweet.all
  end

  # GET /sweets/1
  # GET /sweets/1.json
  def show
  end

  # GET /sweets/new
  def new
    @sweet = Sweet.new
  end

  # GET /sweets/1/edit
  def edit
  end

  # POST /sweets
  # POST /sweets.json
  def create
    @sweet = Sweet.new(sweet_params)

    respond_to do |format|
      if @sweet.save
        format.html { redirect_to @sweet, notice: 'Sweet was successfully created.' }
        format.json { render :show, status: :created, location: @sweet }
      else
        format.html { render :new }
        format.json { render json: @sweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sweets/1
  # PATCH/PUT /sweets/1.json
  def update
    respond_to do |format|
      if @sweet.update(sweet_params)
        format.html { redirect_to @sweet, notice: 'Sweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @sweet }
      else
        format.html { render :edit }
        format.json { render json: @sweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sweets/1
  # DELETE /sweets/1.json
  def destroy
    @sweet.destroy
    respond_to do |format|
      format.html { redirect_to sweets_url, notice: 'Sweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sweet
      @sweet = Sweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sweet_params
      params.require(:sweet).permit(:name, :description, :picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sweets_helper.rb
module SweetsHelper
end

app/views/bookings/_form.html.erb
<%= form_with(model: booking, local: true) do |form| %>
  <% if booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :booking_name %>
  </div>

  <div class="field">
    <%= form.label :details %>
    <%= form.text_area :details, id: :booking_details %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :booking_email%>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bookings</h1>



<br>

<%= link_to 'New Booking', new_booking_path %>

app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Back', bookings_path %>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Back', bookings_path %>
<h1> Thanks!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cartandcandy</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">CartandCandy</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">

        <li class="active"><a href="/pages/about">about</a></li>
          <li class="active"><a href="/sweets">sweets</a></li>
      </ul>
    </div>
  </div>
</nav>

    <div class="container">
      <%= image_tag "logo.png" %>
      <%= image_tag "logo.png" %>
      <%= image_tag "logo.png" %>
      <%= yield %>

    </div>
    <footer>
  <div class="container">
    Rails Girls <%= Time.now.year %>
  </div>
</footer>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.js"></script>
  </body>
</html>

app/views/pages/about.html.erb
<h3>CartandCandy provides the worlds best candy right at your doorstep and/or for any occasion</h1>
<p>Founded by Aaron, Cart and Candy has rapidly expanded over the last few years!</p>

app/views/sweets/_form.html.erb
<%= form_with(model: sweet, local: true) do |form| %>
  <% if sweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sweet.errors.count, "error") %> prohibited this sweet from being saved:</h2>

      <ul>
      <% sweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :sweet_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :sweet_description %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture, id: :sweet_picture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sweets/edit.html.erb
<h1>Editing Sweet</h1>

<%= render 'form', sweet: @sweet %>

<%= link_to 'Show', @sweet %> |
<%= link_to 'Back', sweets_path %>

app/views/sweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>CartandCandy</h1>
<h2>Welcome to the worlds famous candy store</h2>




<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sweets.each do |sweet| %>
      <tr>
        <td><%= sweet.name %></td>


        <td><%= sweet.description %></td>
        <td><%= image_tag(sweet.picture_url, width: 100) if sweet.picture.present? %></td>
        <td><%= link_to 'Show', sweet %></td>
        <td><%= link_to 'Edit', edit_sweet_path(sweet) %></td>
        <td><%= link_to 'Destroy', sweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sweet', new_sweet_path %>

app/views/sweets/new.html.erb
<h1>New Sweet</h1>

<%= render 'form', sweet: @sweet %>

<%= link_to 'Back', sweets_path %>

app/views/sweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sweet.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @sweet.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@sweet.picture_url, width: 600) if @sweet.picture.present? %>
</p>

<%= link_to 'Edit', edit_sweet_path(@sweet) %> |
<%= link_to 'Back', sweets_path %>